AY2324S1-CS2103T-W10-1/tp

- docs/_sass/minima/_base.scss
Closes #35
This PR updates some styling in the print format / PDF generation of the document.
> Update site-wide settings

- docs/team/ravern.md
> Add skeletal PPP for ravern

- docs/team/lheng1.md
This PR creates a Project Portfolio Page (PPP) for Heng Yi.
> Add skeletal version of personal PPP

- docs/DeveloperGuide.md
Closes #40 
Add non-functional requirements and glossary terms to the developer guide.
> Add non-functional requirements and glossary terms

- docs/DeveloperGuide.md
Closes #45 
This PR updates target user profile, value proposition, and user stories in the Developer's Guide page of our project website.
> Update target user profile, value proposition, and user stories

- docs/DeveloperGuide.md
Closes #46 
This PR updates the use cases section in the Developer's Guide of our project website.
> Add use case of edit and compare applicant

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Gpa.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/GpaTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
This PR follows up on #62 and fixes #63 by refactoring the type of `Gpa` class to be a `double` instead of `String`.
> Refactor Gpa to be double

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Attachment.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedAttachment.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/model/person/AttachmentTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
This is in preparation for adding the attach command, as mentioned in #12.
> Add Attachment model type

- docs/UserGuide.md
This PR updates the bookmark and view features in the UG.
> Update bookmark and view in UG

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/BookmarkCommand.java
- src/main/java/seedu/address/logic/commands/UnbookmarkCommand.java
- src/test/java/seedu/address/logic/commands/BookmarkCommandTest.java
- src/test/java/seedu/address/logic/commands/UnbookmarkCommandTest.java
> Update success messages

- docs/DeveloperGuide.md
This PR adds the text portion of the bookmark/unbookmark command in the DG.
> Add text portion of bookmark command in DG

- docs/DeveloperGuide.md
Updates some brief information about the `attach` command into the Developer Guide.
> Update attach command implementation into DG

- src/main/java/seedu/address/logic/commands/AttachCommand.java
- src/main/java/seedu/address/logic/commands/ImportCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/AttachCommandParser.java
- src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Closes #102.
This PR adds the `import` command. 
```
import Downloads/all-applicants.csv
```
These will be fixed in follow-up PRs.
> Add import command

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Closes #170.
This PR fixes a bug in the UI from the Clear Command.
> Fix bug in Clear Command

- src/main/java/seedu/address/ui/HelpWindow.java
Closes #113.
This PR corrects the link provided to the product User Guide (UG) in the help window.
> Fix Help window link error

- docs/UserGuide.md
Closes #143, #148, #125.
This PR updates minor issues in the UG.
> Fix minor UG issues

- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Closes #129.
This PR removes the find command functionality.
> Remove find command

- docs/team/nabonitasen.md
This PR Update PPP app description to match team's.
> Update PPP app description to match team's

- src/test/java/seedu/address/model/person/InterviewScoreTest.java
- src/test/java/seedu/address/model/person/PreviousGradeTest.java
This PR adds tests for PreviousGrade and InterviewScore.
> Add tests for PreviousGrade and InterviewScore

- src/main/java/seedu/address/logic/parser/CompareCommandParser.java
- src/main/java/seedu/address/ui/CompareWindow.java
- src/test/java/seedu/address/logic/commands/CompareCommandTest.java
- src/test/java/seedu/address/logic/parser/CompareCommandParserTest.java
- src/test/java/seedu/address/testutil/AnotherPersonBuilder.java
Closes #162 
- This PR fixes compare command not displaying the pop-up window due to the `Optional` parameter `Interview Score`.
- This PR also fixes the error that causes the output of a window even when more than two indexes are given ie.`compare 1 2 3 4` is inputted.
> Fix compare command output bug

- docs/DeveloperGuide.md
Closes #203 
This PR adds the planned enhancements appendix into our Developer Guide.
> Add Planned Enhancements into DG

- docs/DeveloperGuide.md
- docs/UserGuide.md
Closes #123 
This PR amends both the UG and DG.
UG:
- Grammatical errors
- Formatting errors
- Full stops
- Checked expected output and error messages
- Scrolled through every single "<div>" to find the one missing closer
- Some of the prefixes were missing
- Signs of addressbook
DG:
- Realized that Interview Score also can accept more than 2dp so added in the planned enhancements part
> Fix all errors in UG and amended DG

- src/main/java/seedu/address/logic/commands/ImportCommand.java
Improve the code readability for `ImportCommand#execute` as previously it was just one big function.
> Refactor import command
